# ===================================================================
# Spring Boot configuration for the "prod" profile.
#
# This configuration overrides the application.yml file.
#
# ===================================================================


spring:
  application:
    name: batchsearch
#  profiles:
#    active: prod
  jackson:
    serialization:
      indent-output: true
  datasource:
    type: com.zaxxer.hikari.HikariDataSource
    url: ${CCD_URL}
    username: ${CCD_USER}
    password: ${CCD_PASSWORD}
    hikari:
      poolName: Hikari
      auto-commit: false
  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    show-sql: true
    properties:
      hibernate.id.new_generator_mappings: true
      hibernate.connection.provider_disables_autocommit: true
      hibernate.cache.use_second_level_cache: false
      hibernate.cache.use_query_cache: false
      hibernate.generate_statistics: false
      hibernate.default_schema: ccd_app
# Logging
logging:
  level:
    com.zaxxer.hikari.HikariConfig: info
    org.hibernate.SQL: info
    org.hibernate.stat: info
    gov.epa.ccte.api.*: info
    org.springframework: warn

# server
server:
  servlet:
    context-path: /
  #port: 9300
  compression:
    enabled: true
    mime-types: text/html,text/xml,text/plain,text/css, application/javascript, application/json
    min-response-size: 1024

application:
  api-url: https://api-ccte-stg.epa.gov/chemical/list/chemicals/search/by-dtxsid
  api-ghsurl: https://api-ccte-stg.epa.gov/chemical/ghslink/to-dtxsid/
  apikey: 546aa80b-f05c-4126-a303-18dd66eabb9d

# ===================================================================
# Standard Spring Boot properties.
# Full reference is available at:
# http://docs.spring.io/spring-boot/docs/current/reference/html/common-application-properties.html
# ===================================================================
